# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zerously
email: mariano@zerously.com
description: A blog by Mariano Abdala.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zerously.com" # the base hostname & protocol for your site
twitter_username: marianoabdala
github_username:  marianoabdala

# Build settings
markdown: kramdown
