# Site settings
title: Mariano Abdala
email: mariano@zerously.com
description: >
  Writings of Mariano Abdala. iOS Developer, host at @NSCoderBA and organizer at @NSConfArg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zerously.com" # the base hostname & protocol for your site
twitter_username: marianoabdala
github_username:  marianoabdala

# Build settings
markdown: kramdown
future: false